name = "Minecraft Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeff71626b178008c7233d2dff7ab46cc9fa801d01c2cc2d1ccff9baeab7c89d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
